### ISSUE TITLE
new bits of content.

### ISSUE THREAD

**Issue by paulirish** [shinypb/appcachefacts#1]
dont have the time to add these right now so i'm putting em here for safekeeping
### procedure

 http://www.slideshare.net/remy.sharp/html5-tutorial-canvas-offfline-sockets slides 46-48
### caching and appcache

when you rev the appCache .manifest file, the browser collects all the urls of the assets that need to be updated and see if they need cache validation down at the network layer. The etags/lastmodified/expires headers, etc. are considered, with the browser only fetching what is necessary.

If a file listed in the appCache .manifest file is changed, but the .manifest file itself is not updated or reved, even if there are new caching headers  the browser will not refetch.

of course,  in order for the files to refetch, the manifest itself still needs to change

**Comment by shinypb** [comment]
A mild suggestion for slide 48 — window.location.reload(true). The .reload is preferred just for having a bit more semantic meaning behind it, and the true tells the browser to explicitly re-fetch. It's probably voodoo in the case of appcached pages, but I always include it out of habit.

Adding a new fact:
“When updating an existing appcache, the browser sends standard If-Modified-Since headers, so it skips re-downloading files that have not changed.” — any critique before I post it?

— Mark

**Comment by paulirish** [comment]
LGTM

**Comment by shinypb** [comment]
Great; pushed.
